"""Static repository and generated-project inventory for the Copier checker."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


SOURCE_REQUIRED = [
    "CHANGELOG.md",
    ".githooks/pre-commit",
    ".github/hooks/plan-lifecycle.json",
    ".github/workflows/ci.yml",
    ".github/workflows/codex-ci-autofix.yml",
    ".github/codex/prompts/ci-autofix.md",
    "copier.yml",
    "pyproject.toml",
    "uv.lock",
    "SKILL.md",
    "agents/openai.yaml",
    "references/routing.md",
    "references/planning.md",
    "references/validation.md",
    "references/file-management.md",
    "references/orchestration.md",
    "docs/agent/spec-index.yaml",
    "docs/downstream-baselines.yaml",
    "docs/agent/SPEC_AGENT_LOGGING.md",
    "docs/agent/SPEC_CONTEXT_COMPRESSION.md",
    "docs/agent/SPEC_DECISION_AUDIT.md",
    "docs/agent/SPEC_GIT_RETIREMENT.md",
    "docs/agent/SPEC_PLAN_WORKFLOW.md",
    "docs/agent/SPEC_REFERENT_FIRST.md",
    "docs/agent/SPEC_SKILL_AUTHORING.md",
    "docs/agent/SPEC_USER_COMMUNICATION.md",
    "docs/agent/git-retirement.yaml",
    "scripts/AGENTS.md",
    "scripts/agent-log-event.py",
    "scripts/check-agent-log-manifest.py",
    "scripts/check-codex-toml.py",
    "scripts/check-yaml.py",
    "scripts/check-root-agent-policy.py",
    "scripts/create-root-plan.py",
    "scripts/project_workflow/__init__.py",
    "scripts/project_workflow/copier_inventory.py",
    "scripts/project_workflow/plan_authoring.py",
    "scripts/project_workflow/worktree_guard.py",
    "scripts/context-compress.sh",
    "scripts/import-codex-transcript.py",
    "scripts/install-actionlint.sh",
    "scripts/lint-github-actions.sh",
    "scripts/migrate-sequential-plan-worker.py",
    "scripts/manage-plan-worktrees.py",
    "scripts/plan_validation_commands.py",
    "scripts/render-plan-overview.py",
    "scripts/run-sandboxed-plan-worker.py",
    "scripts/snapshot-validation-witness-provenance.py",
    "scripts/summarize-agent-run.py",
    "scripts/verify-downstream-baselines.py",
    "scripts/restructure-plan.py",
    "scripts/parallel-plan-state.py",
    "scripts/run-parallel-plans.py",
    "scripts/orca-coordinator.py",
    "scripts/plan-execution-state.py",
    "scripts/referent-contract.py",
    "scripts/retire-merged-worktrees.py",
    "scripts/sync-plan-to-linear.sh",
    "scripts/validate-changes.py",
    "scripts/validate-copier-update.py",
    "scripts/natural-japanese-evaluation.py",
    "tests/test-natural-japanese.py",
    "tests/fixtures/natural-japanese/scenarios.json",
    "tests/fixtures/natural-japanese/evaluator-prompt.md",
    "tests/fixtures/natural-japanese/evaluation-results.json",
    ".codex/skills/natural-japanese/SKILL.md",
    ".codex/skills/natural-japanese/agents/openai.yaml",
    ".codex/skills/natural-japanese/references/workflow.md",
    ".codex/skills/natural-japanese/references/upstream-adaptation.md",
    ".codex/skills/natural-japanese/scripts/check-japanese-prose.py",
    ".codex/skills/natural-japanese/LICENSE",
    ".agents/skills/natural-japanese/SKILL.md",
    ".codex/skills/verify-copier-update/SKILL.md",
    ".codex/skills/verify-copier-update/agents/openai.yaml",
    ".codex/skills/verify-copier-update/references/verification-contract.md",
    ".codex/skills/verify-copier-update/scripts/verify-copier-update.py",
    ".codex/skills/verify-copier-update/scripts/triage-copier-update.py",
    ".codex/skills/verify-copier-update/scripts/check-triage-coverage.py",
    ".codex/skills/verify-copier-update/references/update-triage.yaml",
    ".codex/skills/mcp-ops/references/provider-call-execution-context.md",
    "template/AGENTS.md.jinja",
    "template/README.md.jinja",
    "template/.project-agent-workflow/AGENTS.md.jinja",
    "template/.project-agent-workflow/README.md",
    "template/.project-agent-workflow/human-report.json.jinja",
    "template/.project-agent-workflow/ownership.yaml",
    "template/.githooks/pre-commit",
    "template/.github/hooks/plan-lifecycle.json",
    "template/.github/workflows/project-agent-workflow.yml",
    "template/.github/workflows/codex-ci-autofix.yml.jinja",
    "template/.github/codex/prompts/ci-autofix.md",
    "template/.gitignore.jinja",
    "template/.codex/config.toml.jinja",
    "template/.codex/hooks.json.jinja",
    "template/.codex/agents/change_reviewer.toml",
    "template/.codex/agents/docs_researcher.toml",
    "template/.codex/agents/evidence_synthesizer.toml",
    "template/.codex/agents/fast_scoped_worker.toml",
    "template/.codex/agents/repo_explorer.toml",
    "template/.codex/agents/scoped_worker.toml",
    "template/.codex/agents/sequential_plan_worker.toml",
    "template/.codex/hooks/agent_log_event.py",
    "template/.codex/hooks/pre_tool_hardening_gate.py",
    "template/.codex/hooks/semantic_guard_advisory.py",
    "template/.codex/hooks/stop_review_gate.py",
    "template/.project-agent-workflow/hooks/agent_log_event.py",
    "template/.project-agent-workflow/hooks/pre_tool_hardening_gate.py",
    "template/.project-agent-workflow/hooks/semantic_guard_advisory.py",
    "template/.project-agent-workflow/hooks/stop_review_gate.py",
    "template/.agents/skills/define-referents-first/SKILL.md",
    "template/.agents/skills/decision-audit/SKILL.md",
    "template/.agents/skills/graph-memory/SKILL.md",
    "template/.agents/skills/implementation-guidelines/SKILL.md",
    "template/.agents/skills/linear-ops/SKILL.md",
    "template/.agents/skills/mcp-ops/SKILL.md",
    "template/.agents/skills/plan-archive/SKILL.md",
    "template/.agents/skills/sequential-plan-orchestrator/SKILL.md",
    "template/.agents/skills/write-for-reader/SKILL.md",
    "template/.agents/skills/browser-ops/SKILL.md",
    "template/.agents/skills/verify-copier-update/SKILL.md",
    "template/.agents/skills/natural-japanese/SKILL.md",
    "template/.project-agent-workflow/skills/define-referents-first/SKILL.md",
    "template/.project-agent-workflow/skills/define-referents-first/agents/openai.yaml",
    "template/.project-agent-workflow/skills/define-referents-first/references/workflow.md",
    "template/.project-agent-workflow/skills/decision-audit/SKILL.md",
    "template/.project-agent-workflow/skills/decision-audit/agents/openai.yaml",
    "template/.project-agent-workflow/skills/decision-audit/references/implementation-preflight.md",
    "template/.project-agent-workflow/skills/graph-memory/SKILL.md",
    "template/.project-agent-workflow/skills/graph-memory/agents/openai.yaml",
    "template/.project-agent-workflow/skills/implementation-guidelines/SKILL.md",
    "template/.project-agent-workflow/skills/implementation-guidelines/agents/openai.yaml",
    "template/.project-agent-workflow/skills/linear-ops/SKILL.md",
    "template/.project-agent-workflow/skills/linear-ops/agents/openai.yaml",
    "template/.project-agent-workflow/skills/mcp-ops/SKILL.md",
    "template/.project-agent-workflow/skills/mcp-ops/agents/openai.yaml",
    "template/.project-agent-workflow/skills/mcp-ops/references/provider-call-execution-context.md",
    "template/.project-agent-workflow/skills/plan-archive/SKILL.md",
    "template/.project-agent-workflow/skills/plan-archive/agents/openai.yaml",
    "template/.project-agent-workflow/skills/sequential-plan-orchestrator/SKILL.md",
    "template/.project-agent-workflow/skills/sequential-plan-orchestrator/agents/openai.yaml",
    "template/.project-agent-workflow/skills/write-for-reader/SKILL.md",
    "template/.project-agent-workflow/skills/write-for-reader/agents/openai.yaml",
    "template/.project-agent-workflow/skills/browser-ops/SKILL.md",
    "template/.project-agent-workflow/skills/browser-ops/agents/openai.yaml",
    "template/.project-agent-workflow/skills/browser-ops/references/browser-run-policy.md",
    "template/.project-agent-workflow/skills/verify-copier-update/SKILL.md",
    "template/.project-agent-workflow/skills/verify-copier-update/agents/openai.yaml",
    "template/.project-agent-workflow/skills/verify-copier-update/references/verification-contract.md",
    "template/.project-agent-workflow/skills/verify-copier-update/scripts/verify-copier-update.py",
    "template/.project-agent-workflow/skills/verify-copier-update/scripts/triage-copier-update.py",
    "template/.project-agent-workflow/skills/verify-copier-update/scripts/check-triage-coverage.py",
    "template/.project-agent-workflow/skills/verify-copier-update/references/update-triage.yaml",
    "template/.project-agent-workflow/skills/natural-japanese/SKILL.md",
    "template/.project-agent-workflow/skills/natural-japanese/agents/openai.yaml",
    "template/.project-agent-workflow/skills/natural-japanese/references/workflow.md",
    "template/.project-agent-workflow/skills/natural-japanese/references/upstream-adaptation.md",
    "template/.project-agent-workflow/skills/natural-japanese/scripts/check-japanese-prose.py",
    "template/.project-agent-workflow/skills/natural-japanese/LICENSE",
    "template/[[ _copier_conf.answers_file ]].jinja",
    "template/.project-agent-workflow/docs/agent/spec-index.yaml.jinja",
    "template/.project-agent-workflow/docs/agent/CODEX_CI_AUTOFIX.md",
    "template/.project-agent-workflow/docs/agent/SPEC_DEVELOPMENT_FLOW.md.jinja",
    "template/.project-agent-workflow/docs/agent/SPEC_ENVIRONMENT.md",
    "template/.project-agent-workflow/docs/agent/SPEC_AGENT_LOGGING.md",
    "template/.project-agent-workflow/docs/agent/SPEC_COPIER_ADOPTION.md",
    "template/.project-agent-workflow/docs/agent/SPEC_CONTEXT_COMPRESSION.md",
    "template/.project-agent-workflow/docs/agent/SPEC_DECISION_AUDIT.md",
    "template/.project-agent-workflow/docs/agent/SPEC_ORCHESTRATION.md",
    "template/.project-agent-workflow/docs/agent/SPEC_VALIDATION.md.jinja",
    "template/.project-agent-workflow/docs/agent/SPEC_GIT_WORKFLOW.md",
    "template/.project-agent-workflow/docs/agent/SPEC_HUMAN_REPORTING.md",
    "template/.project-agent-workflow/docs/agent/SPEC_FILE_MANAGEMENT.md",
    "template/.project-agent-workflow/docs/agent/SPEC_JAPANESE_TECH_WRITING.md",
    "template/.project-agent-workflow/docs/agent/SPEC_EXTERNAL_SERVICES.md.jinja",
    "template/.project-agent-workflow/docs/agent/SPEC_GIT_RETIREMENT.md",
    "template/docs/agent/external-services.yaml.jinja",
    "template/docs/agent/git-retirement.yaml.jinja",
    "template/.project-agent-workflow/docs/agent/SPEC_PLAN_WORKFLOW.md",
    "template/.project-agent-workflow/docs/agent/SPEC_REFERENT_FIRST.md",
    "template/.project-agent-workflow/docs/agent/SPEC_SECURITY.md",
    "template/.project-agent-workflow/docs/agent/SPEC_SKILL_AUTHORING.md",
    "template/.project-agent-workflow/docs/agent/SPEC_UI_DESIGN.md",
    "template/.project-agent-workflow/docs/agent/SPEC_USER_COMMUNICATION.md",
    "template/docs/agent/PROJECT_ENVIRONMENT.md",
    "template/docs/agent/PROJECT_POLICY.md",
    "template/docs/agent/PROJECT_UI_DESIGN.md",
    "template/docs/plan/README.md",
    "template/docs/plan/checked.md",
    "template/docs/plan/replanned.md",
    "template/docs/plan/plan.md",
    "template/docs/plan/active/README.md",
    "template/docs/plan/backlog/README.md",
    "template/docs/plan/shelved/README.md",
    "template/docs/plan/handoffs/README.md",
    "template/docs/plan/sub-agents/custom-agents.md",
    "template/docs/plan/sub-agents/helper-prompts.md",
    "template/.project-agent-workflow/scripts/create-plan.sh",
    "template/.project-agent-workflow/scripts/manage-plan-worktrees.py",
    "template/.project-agent-workflow/scripts/next-plan-id.sh",
    "template/.project-agent-workflow/scripts/promote-plan.sh",
    "template/.project-agent-workflow/scripts/shelve-plan.sh",
    "template/.project-agent-workflow/scripts/complete-plan.sh",
    "template/.project-agent-workflow/scripts/check-agent-completion.sh",
    "template/.project-agent-workflow/scripts/finalize-active-plan.sh",
    "template/.project-agent-workflow/scripts/check-agent-log-manifest.py",
    "template/.project-agent-workflow/scripts/agent_log_manifest.py",
    "template/.project-agent-workflow/scripts/check-codex-toml.py",
    "template/.project-agent-workflow/scripts/check-external-service-policy.py",
    "template/.project-agent-workflow/scripts/context-compress.sh",
    "template/.project-agent-workflow/scripts/import-codex-transcript.py",
    "template/.project-agent-workflow/scripts/human-report.py",
    "template/.project-agent-workflow/scripts/lint-plan-docs.sh",
    "template/.project-agent-workflow/scripts/format-plan-docs.sh",
    "template/.project-agent-workflow/scripts/select-task-context.sh",
    "template/.project-agent-workflow/scripts/clean-handoffs.sh",
    "template/.project-agent-workflow/scripts/lint-plan-docs.py",
    "template/.project-agent-workflow/scripts/migrate-legacy-template-files.py",
    "template/.project-agent-workflow/scripts/migrate-sequential-plan-worker.py",
    "template/.project-agent-workflow/scripts/planlib.py",
    "template/.project-agent-workflow/scripts/plan_overview.py",
    "template/.project-agent-workflow/scripts/render-plan-overview.py",
    "template/.project-agent-workflow/scripts/restructure-plan.py",
    "template/.project-agent-workflow/scripts/parallel-plan-state.py",
    "template/.project-agent-workflow/scripts/run-parallel-plans.py",
    "template/.project-agent-workflow/scripts/orca-coordinator.py",
    "template/.project-agent-workflow/scripts/plan-execution-state.py",
    "template/.project-agent-workflow/scripts/plan_authoring.py",
    "template/.project-agent-workflow/scripts/plan_validation_commands.py",
    "template/.project-agent-workflow/scripts/run-copier-update.sh",
    "template/.project-agent-workflow/scripts/run-sandboxed-plan-worker.py",
    "template/.project-agent-workflow/scripts/summarize-agent-run.py",
    "template/.project-agent-workflow/scripts/worktree_guard.py",
    "template/.project-agent-workflow/scripts/referent-contract.py",
    "template/.project-agent-workflow/scripts/retire-merged-worktrees.py",
    "template/.project-agent-workflow/scripts/format-plan-docs.py",
    "template/.project-agent-workflow/scripts/search-plan-archive.py",
    "template/.project-agent-workflow/scripts/validate-changes.py",
    "template/.project-agent-workflow/scripts/validate-copier-update.py",
    "template/.project-agent-workflow/scripts/update-from-copier.sh",
    "template/.project-agent-workflow/scripts/security_rules.py",
    "template/.project-agent-workflow/scripts/tool_command_context.py",
    "template/.project-agent-workflow/scripts/security-static-check.py",
    "template/.project-agent-workflow/scripts/skillspector-scan.sh",
    "template/.project-agent-workflow/scripts/structure-map.py",
    "template/.project-agent-workflow/scripts/sync-plan-to-linear.sh",
    "template/.project-agent-workflow/scripts/workflow-status.sh",
    "references/template-development.md",
    "tests/fixtures/typescript.answers.yml",
    "tests/fixtures/python.answers.yml",
    "tests/fixtures/docs.answers.yml",
    "tests/fixtures/copier-pairwise.tsv",
    "tests/copier-minimum.sh",
    "tests/copier-update.sh",
    "tests/assert-generated-semantics.py",
    "tests/root-plan-lifecycle.sh",
    "tests/lib-copier.sh",
    "tests/smoke.sh",
    "tests/prepare-smoke-source.py",
    "tests/AGENTS.md",
    "tests/test-agent-model-profiles.py",
    "tests/test-human-report.py",
    "tests/test-hooks.py",
    "tests/hooks/__init__.py",
    "tests/hooks/support.py",
    "tests/hooks/gates.py",
    "tests/hooks/logging.py",
    "tests/hooks/context.py",
    "tests/hooks/semantic.py",
    "tests/test-copier-migration.py",
    "tests/test-copier-adoption.py",
    "tests/test-referent-contract.py",
    "tests/test-sandboxed-plan-worker.py",
    "tests/test-validation-tools.py",
    "tests/test-verify-copier-update.py",
    "tests/test-copier-fixture-validator.py",
    "tests/select-copier-fixture-validator-tests.py",
    "tests/copier_fixture_validator/__init__.py",
    "tests/copier_fixture_validator/support.py",
    "tests/copier_fixture_validator/contract.py",
    "tests/copier_fixture_validator/inventory.py",
    "tests/copier_fixture_validator/execution.py",
    "tests/copier_fixture_validator/grammar.py",
    "tests/copier_fixture_validator/placement.py",
    "tests/validation_tools/__init__.py",
    "tests/validation_tools/support.py",
    "tests/validation_tools/plan.py",
    "tests/validation_tools/external.py",
    "tests/validation_tools/changes.py",
    "tests/validation_tools/generated.py",
    "tests/validation_tools/smoke_source.py",
    "tests/fixtures/referent-contract/scenarios.json",
    "tests/fixtures/referent-contract/evaluation-protocol.md",
    "tests/fixtures/write-for-reader/scenarios.json",
    "tests/fixtures/browser-ops/scenarios.json",
    "tests/fixtures/mcp-ops/scenarios.json",
    "tests/fixtures/orchestration/staged-acceptance.json",
    "tests/fixtures/orchestration/staged-baseline-events.json",
    "tests/fixtures/orchestration/staged-holdout-events.json",
    "tests/fixtures/orchestration/staged-paired-measured-example.json",
    "tests/fixtures/orchestration/plan-restructuring-scenarios.json",
    "tests/fixtures/orchestration/plan-restructuring-holdout.json",
    "tests/fixtures/orchestration/worker-contract-scenarios.json",
    "tests/fixtures/orchestration/worker-contract-holdout.json",
    "tests/fixtures/orchestration/worker-completion-receipt-scenarios.json",
    "tests/fixtures/orchestration/worker-completion-receipt-holdout.json",
    "tests/fixtures/orchestration/worker-completion-receipt-holdout-v2.json",
    "tests/fixtures/orchestration/worker-completion-receipt-evidence.json",
    "scripts/init-project-workflow.sh",
    "scripts/adopt-to-namespaced-layout.py",
    "scripts/migrate-to-namespaced-layout.py",
    "scripts/update_hook_wiring.py",
    "scripts/update_agent_model_profiles.py",
]

GENERATED_REQUIRED = [
    ".copier-answers.yml",
    ".gitignore",
    ".githooks/pre-commit",
    ".github/hooks/plan-lifecycle.json",
    ".codex/config.toml",
    ".codex/agents/change_reviewer.toml",
    ".codex/agents/docs_researcher.toml",
    ".codex/agents/evidence_synthesizer.toml",
    ".codex/agents/fast_scoped_worker.toml",
    ".codex/agents/repo_explorer.toml",
    ".codex/agents/scoped_worker.toml",
    ".codex/agents/sequential_plan_worker.toml",
    ".codex/hooks/agent_log_event.py",
    ".codex/hooks/pre_tool_hardening_gate.py",
    ".codex/hooks/semantic_guard_advisory.py",
    ".codex/hooks/stop_review_gate.py",
    ".project-agent-workflow/AGENTS.md",
    ".project-agent-workflow/README.md",
    ".project-agent-workflow/human-report.json",
    ".project-agent-workflow/ownership.yaml",
    ".project-agent-workflow/hooks/agent_log_event.py",
    ".project-agent-workflow/hooks/pre_tool_hardening_gate.py",
    ".project-agent-workflow/hooks/semantic_guard_advisory.py",
    ".project-agent-workflow/hooks/stop_review_gate.py",
    ".agents/skills/define-referents-first/SKILL.md",
    ".agents/skills/decision-audit/SKILL.md",
    ".agents/skills/graph-memory/SKILL.md",
    ".agents/skills/implementation-guidelines/SKILL.md",
    ".agents/skills/linear-ops/SKILL.md",
    ".agents/skills/mcp-ops/SKILL.md",
    ".agents/skills/plan-archive/SKILL.md",
    ".agents/skills/sequential-plan-orchestrator/SKILL.md",
    ".agents/skills/write-for-reader/SKILL.md",
    ".agents/skills/browser-ops/SKILL.md",
    ".agents/skills/verify-copier-update/SKILL.md",
    ".agents/skills/natural-japanese/SKILL.md",
    ".project-agent-workflow/skills/define-referents-first/SKILL.md",
    ".project-agent-workflow/skills/define-referents-first/agents/openai.yaml",
    ".project-agent-workflow/skills/define-referents-first/references/workflow.md",
    ".project-agent-workflow/skills/decision-audit/SKILL.md",
    ".project-agent-workflow/skills/decision-audit/agents/openai.yaml",
    ".project-agent-workflow/skills/decision-audit/references/implementation-preflight.md",
    ".project-agent-workflow/skills/graph-memory/SKILL.md",
    ".project-agent-workflow/skills/graph-memory/agents/openai.yaml",
    ".project-agent-workflow/skills/implementation-guidelines/SKILL.md",
    ".project-agent-workflow/skills/implementation-guidelines/agents/openai.yaml",
    ".project-agent-workflow/skills/linear-ops/SKILL.md",
    ".project-agent-workflow/skills/linear-ops/agents/openai.yaml",
    ".project-agent-workflow/skills/mcp-ops/SKILL.md",
    ".project-agent-workflow/skills/mcp-ops/agents/openai.yaml",
    ".project-agent-workflow/skills/mcp-ops/references/provider-call-execution-context.md",
    ".project-agent-workflow/skills/plan-archive/SKILL.md",
    ".project-agent-workflow/skills/plan-archive/agents/openai.yaml",
    ".project-agent-workflow/skills/sequential-plan-orchestrator/SKILL.md",
    ".project-agent-workflow/skills/sequential-plan-orchestrator/agents/openai.yaml",
    ".project-agent-workflow/skills/write-for-reader/SKILL.md",
    ".project-agent-workflow/skills/write-for-reader/agents/openai.yaml",
    ".project-agent-workflow/skills/browser-ops/SKILL.md",
    ".project-agent-workflow/skills/browser-ops/agents/openai.yaml",
    ".project-agent-workflow/skills/browser-ops/references/browser-run-policy.md",
    ".project-agent-workflow/skills/verify-copier-update/SKILL.md",
    ".project-agent-workflow/skills/verify-copier-update/agents/openai.yaml",
    ".project-agent-workflow/skills/verify-copier-update/references/verification-contract.md",
    ".project-agent-workflow/skills/verify-copier-update/scripts/verify-copier-update.py",
    ".project-agent-workflow/skills/natural-japanese/SKILL.md",
    ".project-agent-workflow/skills/natural-japanese/agents/openai.yaml",
    ".project-agent-workflow/skills/natural-japanese/references/workflow.md",
    ".project-agent-workflow/skills/natural-japanese/references/upstream-adaptation.md",
    ".project-agent-workflow/skills/natural-japanese/scripts/check-japanese-prose.py",
    ".project-agent-workflow/skills/natural-japanese/LICENSE",
    "AGENTS.md",
    "README.md",
    ".github/workflows/project-agent-workflow.yml",
    ".github/codex/prompts/ci-autofix.md",
    ".project-agent-workflow/docs/agent/spec-index.yaml",
    ".project-agent-workflow/docs/agent/CODEX_CI_AUTOFIX.md",
    ".project-agent-workflow/docs/agent/SPEC_DEVELOPMENT_FLOW.md",
    ".project-agent-workflow/docs/agent/SPEC_ENVIRONMENT.md",
    ".project-agent-workflow/docs/agent/SPEC_AGENT_LOGGING.md",
    ".project-agent-workflow/docs/agent/SPEC_COPIER_ADOPTION.md",
    ".project-agent-workflow/docs/agent/SPEC_CONTEXT_COMPRESSION.md",
    ".project-agent-workflow/docs/agent/SPEC_DECISION_AUDIT.md",
    ".project-agent-workflow/docs/agent/SPEC_FILE_MANAGEMENT.md",
    ".project-agent-workflow/docs/agent/SPEC_EXTERNAL_SERVICES.md",
    ".project-agent-workflow/docs/agent/SPEC_GIT_RETIREMENT.md",
    "docs/agent/external-services.yaml",
    "docs/agent/git-retirement.yaml",
    ".project-agent-workflow/docs/agent/SPEC_GIT_WORKFLOW.md",
    ".project-agent-workflow/docs/agent/SPEC_HUMAN_REPORTING.md",
    ".project-agent-workflow/docs/agent/SPEC_ORCHESTRATION.md",
    ".project-agent-workflow/docs/agent/SPEC_JAPANESE_TECH_WRITING.md",
    ".project-agent-workflow/docs/agent/SPEC_PLAN_WORKFLOW.md",
    ".project-agent-workflow/docs/agent/SPEC_REFERENT_FIRST.md",
    ".project-agent-workflow/docs/agent/SPEC_SECURITY.md",
    ".project-agent-workflow/docs/agent/SPEC_SKILL_AUTHORING.md",
    ".project-agent-workflow/docs/agent/SPEC_UI_DESIGN.md",
    ".project-agent-workflow/docs/agent/SPEC_USER_COMMUNICATION.md",
    "docs/agent/PROJECT_ENVIRONMENT.md",
    "docs/agent/PROJECT_POLICY.md",
    "docs/agent/PROJECT_UI_DESIGN.md",
    ".project-agent-workflow/docs/agent/SPEC_VALIDATION.md",
    "docs/plan/README.md",
    "docs/plan/backlog/README.md",
    "docs/plan/shelved/README.md",
    "docs/plan/checked.md",
    "docs/plan/replanned.md",
    "docs/plan/handoffs/README.md",
    "docs/plan/sub-agents/custom-agents.md",
    "docs/plan/sub-agents/helper-prompts.md",
    "docs/plan/plan.md",
    ".project-agent-workflow/scripts/check-agent-completion.sh",
    ".project-agent-workflow/scripts/finalize-active-plan.sh",
    ".project-agent-workflow/scripts/check-agent-log-manifest.py",
    ".project-agent-workflow/scripts/agent_log_manifest.py",
    ".project-agent-workflow/scripts/check-codex-toml.py",
    ".project-agent-workflow/scripts/check-external-service-policy.py",
    ".project-agent-workflow/scripts/context-compress.sh",
    ".project-agent-workflow/scripts/import-codex-transcript.py",
    ".project-agent-workflow/scripts/human-report.py",
    ".project-agent-workflow/scripts/complete-plan.sh",
    ".project-agent-workflow/scripts/workflow-status.sh",
    ".project-agent-workflow/scripts/create-plan.sh",
    ".project-agent-workflow/scripts/format-plan-docs.py",
    ".project-agent-workflow/scripts/select-task-context.sh",
    ".project-agent-workflow/scripts/clean-handoffs.sh",
    ".project-agent-workflow/scripts/lint-plan-docs.sh",
    ".project-agent-workflow/scripts/format-plan-docs.sh",
    ".project-agent-workflow/scripts/lint-plan-docs.py",
    ".project-agent-workflow/scripts/migrate-legacy-template-files.py",
    ".project-agent-workflow/scripts/migrate-sequential-plan-worker.py",
    ".project-agent-workflow/scripts/manage-plan-worktrees.py",
    ".project-agent-workflow/scripts/next-plan-id.sh",
    ".project-agent-workflow/scripts/planlib.py",
    ".project-agent-workflow/scripts/plan_overview.py",
    ".project-agent-workflow/scripts/render-plan-overview.py",
    ".project-agent-workflow/scripts/restructure-plan.py",    ".project-agent-workflow/scripts/parallel-plan-state.py",
    ".project-agent-workflow/scripts/run-parallel-plans.py",
    ".project-agent-workflow/scripts/plan-execution-state.py",
    ".project-agent-workflow/scripts/plan_authoring.py",
    ".project-agent-workflow/scripts/plan_validation_commands.py",
    ".project-agent-workflow/scripts/run-copier-update.sh",
    ".project-agent-workflow/scripts/run-sandboxed-plan-worker.py",
    ".project-agent-workflow/scripts/summarize-agent-run.py",
    ".project-agent-workflow/scripts/worktree_guard.py",
    ".project-agent-workflow/scripts/referent-contract.py",
    ".project-agent-workflow/scripts/retire-merged-worktrees.py",
    ".project-agent-workflow/scripts/promote-plan.sh",
    ".project-agent-workflow/scripts/shelve-plan.sh",
    ".project-agent-workflow/scripts/search-plan-archive.py",
    ".project-agent-workflow/scripts/security_rules.py",
    ".project-agent-workflow/scripts/tool_command_context.py",
    ".project-agent-workflow/scripts/structure-map.py",
    ".project-agent-workflow/scripts/validate-changes.py",
    ".project-agent-workflow/scripts/validate-copier-update.py",
    ".project-agent-workflow/scripts/update-from-copier.sh",
    ".project-agent-workflow/scripts/security-static-check.py",
    ".project-agent-workflow/scripts/sync-plan-to-linear.sh",
]

SOURCE_SHELL_LINT = [
    path
    for path in SOURCE_REQUIRED
    if path.endswith(".sh") or path.endswith("/pre-commit")
]
SOURCE_PYTHON_COMPILE = [path for path in SOURCE_REQUIRED if path.endswith(".py")]


QUESTIONS = {
    "project_name",
    "project_slug",
    "project_purpose",
    "primary_language",
    "human_report_mode",
    "human_report_shared_mode",
    "codex_hooks_mode",
    "skillspector_mode",
    "external_access_profile",
    "mcp_policy_mode",
    "linear_sync_mode",
    "graph_memory_mode",
    "ci_autofix_mode",
}

EXPECTED_CHOICE_VALUES = {
    "primary_language": {"typescript", "python", "mixed", "docs"},
    "human_report_mode": {"disabled", "agent_select_local"},
    "human_report_shared_mode": {"disabled", "explicit_publish"},
    "codex_hooks_mode": {"disabled", "install_templates", "enable_local_logging"},
    "skillspector_mode": {"disabled", "document_optional"},
    "external_access_profile": {"restricted", "task_scoped_default_allow"},
    "mcp_policy_mode": {"disabled", "document_optional"},
    "linear_sync_mode": {"disabled", "document_optional"},
    "graph_memory_mode": {"disabled", "document_optional"},
    "ci_autofix_mode": {"disabled", "patch_only", "direct_push"},
}

EXPECTED_DEFAULT_VALUES = {
    "human_report_mode": "agent_select_local",
    "human_report_shared_mode": "disabled",
    "external_access_profile": "restricted",
    "ci_autofix_mode": "disabled",
}

CONDITIONAL_GENERATED = {
    ".codex/hooks.json": ("codex_hooks_mode", {"enable_local_logging"}),
    ".project-agent-workflow/scripts/skillspector-scan.sh": ("skillspector_mode", {"document_optional"}),
    ".github/workflows/codex-ci-autofix.yml": ("ci_autofix_mode", {"patch_only", "direct_push"}),
}

PAIRWISE_FIXTURE = ROOT / "tests/fixtures/copier-pairwise.tsv"

JAPANESE_RE = re.compile(r"[\u3040-\u30ff\u3400-\u9fff]")

REMOVED_ACTIVATION_QUESTIONS = {
    "use_hooks",
    "use_skillspector",
    "use_mcp_policy",
    "use_linear_sync",
    "use_graph_memory",
}

REMOVED_LOCAL_WORKFLOW_QUESTIONS = {
    "planning_style",
    "use_codex_agents",
    "max_agent_threads",
    "use_plan_lifecycle",
    "use_change_validation",
    "use_security_static",
    "use_structure_scanner",
}
